### ISSUE TITLE
Add a password pattern validation.

### ISSUE THREAD

**Issue by codetheorem** [Bot-Academia/Nebula-Backend#34]
Add a password pattern validation in login and signup routes controllers and integrate that with client side so that we have stronger passwords and it increases the security of user's data.

**Comment by pankajkumarbij** [comment]
Hello 
I want to work on this issue.

**Comment by koolgax99** [comment]
@codetheorem can you lease assign this issue to me

**Comment by codetheorem** [comment]
go ahead @koolgax99

**Comment by koolgax99** [comment]
thankyou @codetheorem. can you please provide the pattern to be validated so that it would be easy for me.

**Comment by codetheorem** [comment]
@koolgax99 add a pattern that requires a minimum of 8 characters and should be alphanumeric. You are free to add any kind of pattern that increases security.

**Comment by koolgax99** [comment]
Okay sir, thankyou for your input!!
